version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "=============== INSTALLING DEPENDENCIES ==============="
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "=============== RUNNING UNIT TESTS WITH COVERAGE ==============="
      - export TEST_MODE=true
      - pytest --cov=app --cov-report=term-missing --cov-fail-under=95

  build:
    commands:
      - echo "=============== LOGGING INTO AMAZON ECR ==============="
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 584763186660.dkr.ecr.us-east-1.amazonaws.com
      - echo "=============== BUILDING DOCKER IMAGE ==============="
      - docker build -t 584763186660.dkr.ecr.us-east-1.amazonaws.com/image-registry-np-dev-miso-devops:latest . --no-cache

  post_build:
    commands:
      - echo "=============== PUSHING DOCKER IMAGE TO AMAZON ECR ==============="
      - docker push 584763186660.dkr.ecr.us-east-1.amazonaws.com/image-registry-np-dev-miso-devops:latest
      - echo "=============== DOCKER IMAGE PUSHED SUCCESSFULLY ==============="

artifacts:
  files:
    - '**/*'